package com.tom.tradeoptimizer.trade;

import com.tom.tradeoptimizer.TradeOptimizer;
import com.tom.tradeoptimizer.config.TradeOptimizerConfig;
import com.tom.tradeoptimizer.config.TradeOptimizerConfig.GearEnchantMode;
import it.unimi.dsi.fastutil.ints.Int2ObjectMap;
import net.minecraft.core.Holder;
import net.minecraft.core.HolderLookup;
import net.minecraft.core.HolderSet;
import net.minecraft.core.component.DataComponents;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceKey;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.tags.EnchantmentTags;
import net.minecraft.util.RandomSource;
import net.minecraft.world.entity.npc.Villager;
import net.minecraft.world.entity.npc.VillagerProfession;
import net.minecraft.world.entity.npc.VillagerTrades;
import net.minecraft.world.flag.FeatureFlags;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.alchemy.Potion;
import net.minecraft.world.item.alchemy.PotionContents;
import net.minecraft.world.item.enchantment.Enchantable;
import net.minecraft.world.item.enchantment.Enchantment;
import net.minecraft.world.item.enchantment.EnchantmentHelper;
import net.minecraft.world.item.enchantment.EnchantmentInstance;
import net.minecraft.world.item.enchantment.ItemEnchantments;
import net.minecraft.world.item.trading.ItemCost;
import net.minecraft.world.item.trading.MerchantOffer;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.function.Predicate;

/**
 * Enumerate the trade pool for a (profession, level) pair and produce min-cost
 * MerchantOffers. Book trades expand into one card per (enchantment × level) so
 * the player can pick Sharpness V at min cost, not just Sharpness I.
 *
 * MC 1.21.1: trades are NOT data-driven (no TradeSet registry like the 26.x line) — the pool
 * is the hardcoded {@link VillagerTrades#TRADES} map of ItemListing arrays per profession and
 * level, generated by calling {@code listing.getOffer(villager, randomSource)}. The min-price
 * trick is therefore even more direct than on 26.x: we hand the listing our own RandomSource.
 * For book trades, vanilla's EnchantBookForEmeralds rolls (1) the enchantment index out of the
 * TRADEABLE tag, (2) the level via Mth.nextInt, then (3+) cost variance — exactly the prefix
 * shape {@link IndexBiasedRandomSource} steers.
 *
 * Synthetic TradeKeys (1.21.1 has no trade registry ids):
 *   tradeoptimizer:listing/&lt;merchantLevel&gt;/&lt;index&gt; — flat trade by pool position
 *   tradeoptimizer:book/&lt;level&gt;/&lt;ench_ns&gt;/&lt;ench_path&gt; — expanded book card
 *
 * When the Villager Trade Rebalance experiment is enabled, vanilla draws from
 * {@link VillagerTrades#EXPERIMENTAL_TRADES} instead — we mirror that so the picker always
 * shows the pool the server would actually use.
 */
public final class OfferFactory {
    private OfferFactory() {}

    private static final String BOOK_PREFIX = "book/";
    private static final String LISTING_PREFIX = "listing/";
    private static final String GEAR_PREFIX = "gear/";
    private static final String ARROW_PREFIX = "arrow/";
    private static final String GEAR_SINGLE = "single/";
    private static final String GEAR_HEADLINE = "headline/";

    /** Vanilla villager enchanted-gear trades roll the enchant level in this base range (5..19). */
    private static final int GEAR_BASE_LEVEL_MIN = 5;
    private static final int GEAR_BASE_LEVEL_MAX = 19;
    private static final int HEADLINE_ATTEMPTS = 256;
    private static final int EMERALD_CAP = 64;

    /** Villager merchant levels run 1 (Novice) .. 5 (Master). */
    private static final int MAX_MERCHANT_LEVEL = 5;

    // -------------------------------------------------------------------------
    // Trade pool access (1.21.1 hardcoded listing tables)
    // -------------------------------------------------------------------------

    private static Int2ObjectMap<VillagerTrades.ItemListing[]> tradeMap(ServerLevel level, VillagerProfession prof) {
        Map<VillagerProfession, Int2ObjectMap<VillagerTrades.ItemListing[]>> source =
                level.enabledFeatures().contains(FeatureFlags.TRADE_REBALANCE)
                        ? VillagerTrades.EXPERIMENTAL_TRADES
                        : VillagerTrades.TRADES;
        Int2ObjectMap<VillagerTrades.ItemListing[]> map = source.get(prof);
        // The experimental table only covers some professions; vanilla falls back too.
        return map != null ? map : VillagerTrades.TRADES.get(prof);
    }

    /** The raw listing array for a (profession, level), or null when the pool has none. */
    public static VillagerTrades.ItemListing[] listingsFor(ServerLevel level, VillagerProfession prof, int merchantLevel) {
        Int2ObjectMap<VillagerTrades.ItemListing[]> map = tradeMap(level, prof);
        return map == null ? null : map.get(merchantLevel);
    }

    // -------------------------------------------------------------------------
    // Enumeration / generation
    // -------------------------------------------------------------------------

    public static List<AvailableTrade> enumerate(ServerLevel level, Villager villager, int merchantLevel) {
        List<AvailableTrade> out = new ArrayList<>();
        VillagerProfession prof = villager.getVillagerData().getProfession();
        VillagerTrades.ItemListing[] listings = listingsFor(level, prof, merchantLevel);
        if (listings == null || listings.length == 0) {
            TradeOptimizer.LOGGER.warn("No trade listings for {} level {}", prof, merchantLevel);
            return out;
        }
        HolderLookup.Provider registries = level.registryAccess();

        for (int i = 0; i < listings.length; i++) {
            TradeKey flatKey = buildListingKey(merchantLevel, i);
            try {
                MerchantOffer preview = listings[i].getOffer(villager, costRandom(villager, flatKey));
                if (preview == null) continue;

                ItemStack result = preview.getResult();
                if (result.is(Items.ENCHANTED_BOOK)) {
                    out.addAll(expandBookTrade(villager, listings[i], registries));
                } else if (result.is(Items.TIPPED_ARROW)) {
                    List<AvailableTrade> arrows = expandArrowTrade(villager, preview, registries);
                    if (arrows.isEmpty()) out.add(new AvailableTrade(flatKey, preview));
                    else out.addAll(arrows);
                } else if (!result.getEnchantments().isEmpty()) {
                    // Enchanted gear: vanilla rolls a random enchantment, so the picker saw ONE card.
                    // Expand into player-choosable cards (issues #4 / #5).
                    List<AvailableTrade> gear = expandGearTrade(level, villager, preview, registries);
                    if (gear.isEmpty()) out.add(new AvailableTrade(flatKey, preview));
                    else out.addAll(gear);
                } else {
                    out.add(new AvailableTrade(flatKey, preview));
                }
            } catch (Exception e) {
                TradeOptimizer.LOGGER.warn("Failed to generate preview for listing {}/{}: {}",
                        merchantLevel, i, e.getMessage());
            }
        }
        return out;
    }

    /**
     * How many enchanted-book trade TEMPLATES the (profession, level) pool contains. Vanilla
     * grants at most this many book trades at that level — each template yields a single book
     * trade — so the picker uses it as the per-level book cap when {@code vanillaBookLimits} is
     * on. Counts raw templates, NOT the per-(enchantment × level) cards they expand into.
     */
    public static int countBookTemplates(ServerLevel level, Villager villager, int merchantLevel) {
        VillagerProfession prof = villager.getVillagerData().getProfession();
        VillagerTrades.ItemListing[] listings = listingsFor(level, prof, merchantLevel);
        if (listings == null) return 0;

        int count = 0;
        for (VillagerTrades.ItemListing listing : listings) {
            try {
                MerchantOffer preview = listing.getOffer(villager, MinRandomSource.INSTANCE);
                if (preview != null && preview.getResult().is(Items.ENCHANTED_BOOK)) count++;
            } catch (Exception e) {
                // Skip — same templates enumerate() would skip; not a book slot we can offer.
            }
        }
        return count;
    }

    public static Optional<MerchantOffer> generate(ServerLevel level, Villager villager, TradeKey key, int merchantLevel) {
        if (isBookKey(key)) {
            return generateBookOffer(level, villager, key, merchantLevel);
        }
        if (isGearKey(key)) {
            return generateGearOffer(level, villager, key, merchantLevel);
        }
        if (isArrowKey(key)) {
            return generateArrowOffer(level, villager, key, merchantLevel);
        }
        ListingRef ref = parseListingKey(key);
        if (ref == null) return Optional.empty();
        VillagerProfession prof = villager.getVillagerData().getProfession();
        VillagerTrades.ItemListing[] listings = listingsFor(level, prof, ref.level());
        if (listings == null || ref.index() < 0 || ref.index() >= listings.length) return Optional.empty();
        try {
            return Optional.ofNullable(listings[ref.index()].getOffer(villager, costRandom(villager, key)));
        } catch (Exception e) {
            TradeOptimizer.LOGGER.warn("Failed to generate offer for trade {}: {}", key.id(), e.getMessage());
            return Optional.empty();
        }
    }

    // -------------------------------------------------------------------------
    // Book enumeration: one card per (enchantment × level)
    // -------------------------------------------------------------------------

    private static List<AvailableTrade> expandBookTrade(Villager villager, VillagerTrades.ItemListing template,
                                                        HolderLookup.Provider registries) {
        List<AvailableTrade> out = new ArrayList<>();
        List<Holder<Enchantment>> tradeable = tradeableEnchantments(registries);

        for (int enchIdx = 0; enchIdx < tradeable.size(); enchIdx++) {
            Holder<Enchantment> ench = tradeable.get(enchIdx);
            Optional<ResourceKey<Enchantment>> enchKey = ench.unwrapKey();
            if (enchKey.isEmpty()) continue;

            int minLvl = ench.value().getMinLevel();
            int maxLvl = ench.value().getMaxLevel();

            for (int lvl = minLvl; lvl <= maxLvl; lvl++) {
                int levelOffset = lvl - minLvl;
                try {
                    TradeKey bookKey = buildSyntheticBookKey(enchKey.get().location(), lvl);
                    MerchantOffer offer = template.getOffer(villager,
                            new IndexBiasedRandomSource(bookCostFallback(villager, bookKey), enchIdx, levelOffset));
                    if (offer == null || !offer.getResult().is(Items.ENCHANTED_BOOK)) continue;
                    out.add(new AvailableTrade(bookKey, offer));
                } catch (Exception e) {
                    // Skip on failure — some enchantments may not be valid for this trade.
                }
            }
        }
        return out;
    }

    private static Optional<MerchantOffer> generateBookOffer(ServerLevel level, Villager villager,
                                                             TradeKey synthetic, int merchantLevel) {
        SyntheticBookKey parsed = parseSyntheticBook(synthetic);
        if (parsed == null) return Optional.empty();

        HolderLookup.Provider registries = level.registryAccess();
        VillagerProfession prof = villager.getVillagerData().getProfession();

        // Find enchantment index + min level in the tradeable pool
        List<Holder<Enchantment>> tradeable = tradeableEnchantments(registries);
        int enchIdx = -1;
        int minLevel = 1;
        for (int i = 0; i < tradeable.size(); i++) {
            Holder<Enchantment> h = tradeable.get(i);
            if (h.unwrapKey().map(k -> k.location().equals(parsed.enchantmentId)).orElse(false)) {
                enchIdx = i;
                minLevel = h.value().getMinLevel();
                break;
            }
        }
        if (enchIdx < 0) return Optional.empty();
        int levelOffset = parsed.level - minLevel;
        RandomSource costFallback = bookCostFallback(villager, synthetic);

        // A book trade must be regenerated from a book-producing template, which has to come
        // from a level whose pool actually CONTAINS one. Try the pick's own level first, then
        // scan every level — same fallback the 26.x line uses (a librarian's master level may
        // sell no books).
        List<Integer> candidateLevels = new ArrayList<>();
        if (merchantLevel >= 1 && merchantLevel <= MAX_MERCHANT_LEVEL) candidateLevels.add(merchantLevel);
        for (int lvl = 1; lvl <= MAX_MERCHANT_LEVEL; lvl++) {
            if (!candidateLevels.contains(lvl)) candidateLevels.add(lvl);
        }

        for (int lvl : candidateLevels) {
            VillagerTrades.ItemListing[] listings = listingsFor(level, prof, lvl);
            if (listings == null) continue;

            for (int i = 0; i < listings.length; i++) {
                try {
                    MerchantOffer offer = listings[i].getOffer(villager,
                            new IndexBiasedRandomSource(costFallback, enchIdx, levelOffset));
                    if (offer == null || !offer.getResult().is(Items.ENCHANTED_BOOK)) continue;
                    TradeOptimizer.LOGGER.info("[book-regen] resolved {} -> {} via listing {}/{}",
                            synthetic.id(), offer.getResult(), lvl, i);
                    return Optional.of(offer);
                } catch (Exception e) {
                    TradeOptimizer.LOGGER.warn("[book-regen] listing {}/{} threw while regenerating {}",
                            lvl, i, synthetic.id(), e);
                }
            }
        }
        TradeOptimizer.LOGGER.warn("[book-regen] FAILED to regenerate {} (no book template found at any level)",
                synthetic.id());
        return Optional.empty();
    }

    // -------------------------------------------------------------------------
    // Enchanted gear + tipped arrow enumeration / generation (1.21.1)
    // -------------------------------------------------------------------------

    private record EnchPick(Holder<Enchantment> ench, int level) {}

    /** Cost/shape carried over from the vanilla gear / tipped-arrow listing's min preview. */
    private record GearTemplateInfo(ItemCost costA, Optional<ItemCost> costB, int count,
                                    int maxUses, int xp, float priceMultiplier) {
        static GearTemplateInfo from(MerchantOffer o) {
            return new GearTemplateInfo(o.getItemCostA(), o.getItemCostB(), o.getResult().getCount(),
                    o.getMaxUses(), o.getXp(), o.getPriceMultiplier());
        }
    }

    private static List<AvailableTrade> expandGearTrade(ServerLevel level, Villager villager,
                                                        MerchantOffer templatePreview, HolderLookup.Provider registries) {
        List<AvailableTrade> out = new ArrayList<>();
        Optional<HolderSet<Enchantment>> poolOpt = onTradedPool(registries);
        if (poolOpt.isEmpty()) return out;
        HolderSet<Enchantment> pool = poolOpt.get();

        Item item = templatePreview.getResult().getItem();
        ResourceLocation itemId = BuiltInRegistries.ITEM.getKey(item);
        GearTemplateInfo tmpl = GearTemplateInfo.from(templatePreview);
        String profId = professionId(villager);
        ItemStack base = new ItemStack(item, tmpl.count());

        Map<Holder<Enchantment>, Integer> reachable = reachableGearEnchants(base, pool);
        if (reachable.isEmpty()) return out;

        List<Map.Entry<Holder<Enchantment>, Integer>> entries = new ArrayList<>(reachable.entrySet());
        entries.sort((a, b) -> enchId(a.getKey()).compareTo(enchId(b.getKey())));

        GearEnchantMode mode = TradeOptimizerConfig.get().gearEnchantMode();

        for (Map.Entry<Holder<Enchantment>, Integer> e : entries) {
            Holder<Enchantment> ench = e.getKey();
            Optional<ResourceKey<Enchantment>> ek = ench.unwrapKey();
            if (ek.isEmpty()) continue;
            ResourceLocation enchId = ek.get().location();

            if (mode == GearEnchantMode.SINGLE) {
                int maxLvl = e.getValue();
                for (int lvl = ench.value().getMinLevel(); lvl <= maxLvl; lvl++) {
                    TradeKey key = gearSingleKey(itemId, enchId, lvl);
                    MerchantOffer offer = buildGearOffer(level, villager, tmpl, item, profId,
                            GearEnchantMode.SINGLE, ench, lvl, key, pool);
                    if (offer != null) out.add(new AvailableTrade(key, offer));
                }
            } else {
                TradeKey key = gearHeadlineKey(itemId, enchId);
                MerchantOffer offer = buildGearOffer(level, villager, tmpl, item, profId,
                        GearEnchantMode.HEADLINE, ench, 1, key, pool);
                if (offer != null) out.add(new AvailableTrade(key, offer));
            }
        }
        return out;
    }

    /** Every (enchantment → max level) vanilla can roll on {@code base} via the enchanting-table algorithm. */
    private static Map<Holder<Enchantment>, Integer> reachableGearEnchants(ItemStack base, HolderSet<Enchantment> pool) {
        Map<Holder<Enchantment>, Integer> max = new LinkedHashMap<>();
        // 1.21.2 moved enchantability off Item.getEnchantmentValue() onto the ENCHANTABLE component.
        Enchantable enchantable = base.get(DataComponents.ENCHANTABLE);
        if (enchantable == null) return max;
        int enchantability = enchantable.value();
        int spread = enchantability / 4;
        int pMin = Math.max(1, Math.round((GEAR_BASE_LEVEL_MIN + 1) * 0.85f));
        int pMax = Math.round((GEAR_BASE_LEVEL_MAX + 1 + 2 * spread) * 1.15f);
        for (int p = pMin; p <= pMax; p++) {
            List<EnchantmentInstance> avail;
            try {
                avail = EnchantmentHelper.getAvailableEnchantmentResults(p, base, pool.stream());
            } catch (Exception ex) {
                continue;
            }
            for (EnchantmentInstance inst : avail) {
                max.merge(inst.enchantment, inst.level, Math::max);
            }
        }
        return max;
    }

    private static MerchantOffer buildGearOffer(ServerLevel level, Villager villager, GearTemplateInfo tmpl,
                                                Item item, String profId, GearEnchantMode mode,
                                                Holder<Enchantment> ench, int singleLevel,
                                                TradeKey key, HolderSet<Enchantment> pool) {
        ItemStack result = new ItemStack(item, tmpl.count());
        List<EnchPick> finalSet = new ArrayList<>();

        if (mode == GearEnchantMode.SINGLE) {
            result.enchant(ench, singleLevel);
            finalSet.add(new EnchPick(ench, singleLevel));
        } else {
            ItemStack rolled = rollHeadline(level, result, ench, priceSeed(villager, key), pool);
            if (rolled == null) return null;
            result = rolled;
            ItemEnchantments ie = result.getEnchantments();
            for (Holder<Enchantment> h : ie.keySet()) finalSet.add(new EnchPick(h, ie.getLevel(h)));
        }

        ItemCost costA = TradeOptimizerConfig.get().isCostScaling(profId)
                ? scaledCost(finalSet)
                : tmpl.costA();
        return new MerchantOffer(costA, tmpl.costB(), result, tmpl.maxUses(), tmpl.xp(), tmpl.priceMultiplier());
    }

    /** Roll an enchanted item the vanilla way but guarantee {@code headline} ends up on it. Deterministic per seed. */
    private static ItemStack rollHeadline(ServerLevel level, ItemStack base, Holder<Enchantment> headline,
                                          long seed, HolderSet<Enchantment> pool) {
        ResourceLocation targetId = headline.unwrapKey().map(ResourceKey::location).orElse(null);
        if (targetId == null) return null;
        Optional<? extends HolderSet<Enchantment>> poolOpt = Optional.of(pool);
        for (int i = 0; i < HEADLINE_ATTEMPTS; i++) {
            RandomSource r = RandomSource.create(seed * 31L + i);
            int lvl = GEAR_BASE_LEVEL_MIN + r.nextInt(GEAR_BASE_LEVEL_MAX - GEAR_BASE_LEVEL_MIN + 1);
            ItemStack out;
            try {
                out = EnchantmentHelper.enchantItem(r, base.copy(), lvl, level.registryAccess(), poolOpt);
            } catch (Exception ex) {
                continue;
            }
            if (hasEnchant(out, targetId)) return out;
        }
        ItemStack out = base.copy();
        out.enchant(headline, headline.value().getMinLevel());
        return out;
    }

    private static boolean hasEnchant(ItemStack stack, ResourceLocation id) {
        for (Holder<Enchantment> h : stack.getEnchantments().keySet()) {
            if (h.unwrapKey().map(k -> k.location().equals(id)).orElse(false)) return true;
        }
        return false;
    }

    private static ItemCost scaledCost(List<EnchPick> picks) {
        int total = 2;
        for (EnchPick p : picks) {
            total += Math.max(1, p.ench().value().getAnvilCost()) * p.level();
        }
        total = Math.max(1, Math.min(EMERALD_CAP, total));
        return new ItemCost(Items.EMERALD, total);
    }

    private static List<AvailableTrade> expandArrowTrade(Villager villager, MerchantOffer templatePreview,
                                                         HolderLookup.Provider registries) {
        List<AvailableTrade> out = new ArrayList<>();
        GearTemplateInfo tmpl = GearTemplateInfo.from(templatePreview);
        registries.lookupOrThrow(Registries.POTION).listElements().forEach(h -> {
            Potion p = h.value();
            if (p.getEffects().isEmpty()) return;
            Optional<ResourceKey<Potion>> pk = h.unwrapKey();
            if (pk.isEmpty()) return;
            out.add(new AvailableTrade(arrowKey(pk.get().location()), buildArrowOffer(tmpl, h)));
        });
        return out;
    }

    private static MerchantOffer buildArrowOffer(GearTemplateInfo tmpl, Holder<Potion> potion) {
        ItemStack arrow = new ItemStack(Items.TIPPED_ARROW, tmpl.count());
        arrow.set(DataComponents.POTION_CONTENTS, new PotionContents(potion));
        return new MerchantOffer(tmpl.costA(), tmpl.costB(), arrow, tmpl.maxUses(), tmpl.xp(), tmpl.priceMultiplier());
    }

    private static Optional<MerchantOffer> generateGearOffer(ServerLevel level, Villager villager,
                                                             TradeKey key, int merchantLevel) {
        GearKey gk = parseGearKey(key);
        if (gk == null) return Optional.empty();
        HolderLookup.Provider registries = level.registryAccess();

        Item item = registries.lookupOrThrow(Registries.ITEM)
                .get(ResourceKey.create(Registries.ITEM, gk.item()))
                .map(Holder.Reference::value).orElse(null);
        Optional<Holder.Reference<Enchantment>> ench = registries.lookupOrThrow(Registries.ENCHANTMENT)
                .get(ResourceKey.create(Registries.ENCHANTMENT, gk.ench()));
        if (item == null || ench.isEmpty()) return Optional.empty();

        Optional<HolderSet<Enchantment>> pool = onTradedPool(registries);
        if (pool.isEmpty()) return Optional.empty();

        GearTemplateInfo tmpl = findTemplate(level, villager, merchantLevel,
                o -> o.getResult().getItem() == item && !o.getResult().getEnchantments().isEmpty());
        if (tmpl == null) {
            TradeOptimizer.LOGGER.warn("[gear-regen] no gear template for {}", key.id());
            return Optional.empty();
        }
        return Optional.ofNullable(buildGearOffer(level, villager, tmpl, item, professionId(villager),
                gk.mode(), ench.get(), gk.level(), key, pool.get()));
    }

    private static Optional<MerchantOffer> generateArrowOffer(ServerLevel level, Villager villager,
                                                              TradeKey key, int merchantLevel) {
        ResourceLocation potionId = parseArrowKey(key);
        if (potionId == null) return Optional.empty();
        HolderLookup.Provider registries = level.registryAccess();
        Optional<Holder.Reference<Potion>> potion = registries.lookupOrThrow(Registries.POTION)
                .get(ResourceKey.create(Registries.POTION, potionId));
        if (potion.isEmpty()) return Optional.empty();

        GearTemplateInfo tmpl = findTemplate(level, villager, merchantLevel,
                o -> o.getResult().is(Items.TIPPED_ARROW));
        if (tmpl == null) {
            TradeOptimizer.LOGGER.warn("[arrow-regen] no tipped-arrow template for {}", key.id());
            return Optional.empty();
        }
        return Optional.of(buildArrowOffer(tmpl, potion.get()));
    }

    /** Scan this villager's listing pools for a min-preview matching the predicate; return its cost/shape. */
    private static GearTemplateInfo findTemplate(ServerLevel level, Villager villager, int merchantLevel,
                                                 Predicate<MerchantOffer> match) {
        VillagerProfession prof = villager.getVillagerData().getProfession();
        List<Integer> candidateLevels = new ArrayList<>();
        if (merchantLevel >= 1 && merchantLevel <= MAX_MERCHANT_LEVEL) candidateLevels.add(merchantLevel);
        for (int lvl = 1; lvl <= MAX_MERCHANT_LEVEL; lvl++) {
            if (!candidateLevels.contains(lvl)) candidateLevels.add(lvl);
        }
        for (int lvl : candidateLevels) {
            VillagerTrades.ItemListing[] listings = listingsFor(level, prof, lvl);
            if (listings == null) continue;
            for (int i = 0; i < listings.length; i++) {
                try {
                    MerchantOffer preview = listings[i].getOffer(villager, costRandom(villager, buildListingKey(lvl, i)));
                    if (preview != null && match.test(preview)) return GearTemplateInfo.from(preview);
                } catch (Exception e) {
                    // skip
                }
            }
        }
        return null;
    }

    // ---- gear / arrow synthetic key codec (length-prefixed; ResourceLocation paths may contain '/') ----

    private record GearKey(GearEnchantMode mode, ResourceLocation item, ResourceLocation ench, int level) {}

    public static boolean isGearKey(TradeKey key) {
        return key.id().getNamespace().equals(TradeOptimizer.MOD_ID) && key.id().getPath().startsWith(GEAR_PREFIX);
    }

    public static boolean isArrowKey(TradeKey key) {
        return key.id().getNamespace().equals(TradeOptimizer.MOD_ID) && key.id().getPath().startsWith(ARROW_PREFIX);
    }

    /** For a HEADLINE gear key, the enchantment the player chose; empty for SINGLE / non-gear. */
    public static Optional<ResourceLocation> headlineEnchantId(TradeKey key) {
        if (!isGearKey(key)) return Optional.empty();
        GearKey gk = parseGearKey(key);
        if (gk == null || gk.mode() != GearEnchantMode.HEADLINE) return Optional.empty();
        return Optional.of(gk.ench());
    }

    static TradeKey gearSingleKey(ResourceLocation item, ResourceLocation ench, int level) {
        StringBuilder sb = new StringBuilder(GEAR_PREFIX).append(GEAR_SINGLE).append(level).append('/');
        appendId(sb, item);
        sb.append('/');
        appendId(sb, ench);
        return new TradeKey(ResourceLocation.fromNamespaceAndPath(TradeOptimizer.MOD_ID, sb.toString()));
    }

    static TradeKey gearHeadlineKey(ResourceLocation item, ResourceLocation ench) {
        StringBuilder sb = new StringBuilder(GEAR_PREFIX).append(GEAR_HEADLINE);
        appendId(sb, item);
        sb.append('/');
        appendId(sb, ench);
        return new TradeKey(ResourceLocation.fromNamespaceAndPath(TradeOptimizer.MOD_ID, sb.toString()));
    }

    static TradeKey arrowKey(ResourceLocation potion) {
        StringBuilder sb = new StringBuilder(ARROW_PREFIX);
        appendId(sb, potion);
        return new TradeKey(ResourceLocation.fromNamespaceAndPath(TradeOptimizer.MOD_ID, sb.toString()));
    }

    private static void appendId(StringBuilder sb, ResourceLocation id) {
        String[] pathSegs = id.getPath().split("/");
        sb.append(1 + pathSegs.length).append('/').append(id.getNamespace());
        for (String seg : pathSegs) sb.append('/').append(seg);
    }

    private static ResourceLocation readId(String[] parts, int[] cur) {
        if (cur[0] >= parts.length) return null;
        int count;
        try {
            count = Integer.parseInt(parts[cur[0]++]);
        } catch (NumberFormatException e) {
            return null;
        }
        if (count < 2 || cur[0] + count > parts.length) return null;
        String ns = parts[cur[0]++];
        StringBuilder path = new StringBuilder();
        for (int i = 1; i < count; i++) {
            if (i > 1) path.append('/');
            path.append(parts[cur[0]++]);
        }
        try {
            return ResourceLocation.fromNamespaceAndPath(ns, path.toString());
        } catch (Exception e) {
            return null;
        }
    }

    static GearKey parseGearKey(TradeKey key) {
        String path = key.id().getPath();
        if (!path.startsWith(GEAR_PREFIX)) return null;
        String rest = path.substring(GEAR_PREFIX.length());
        GearEnchantMode mode;
        String body;
        if (rest.startsWith(GEAR_SINGLE)) {
            mode = GearEnchantMode.SINGLE;
            body = rest.substring(GEAR_SINGLE.length());
        } else if (rest.startsWith(GEAR_HEADLINE)) {
            mode = GearEnchantMode.HEADLINE;
            body = rest.substring(GEAR_HEADLINE.length());
        } else {
            return null;
        }
        String[] parts = body.split("/");
        int[] cur = {0};
        int level = 1;
        if (mode == GearEnchantMode.SINGLE) {
            if (cur[0] >= parts.length) return null;
            try {
                level = Integer.parseInt(parts[cur[0]++]);
            } catch (NumberFormatException e) {
                return null;
            }
        }
        ResourceLocation item = readId(parts, cur);
        ResourceLocation ench = readId(parts, cur);
        if (item == null || ench == null) return null;
        return new GearKey(mode, item, ench, level);
    }

    static ResourceLocation parseArrowKey(TradeKey key) {
        String path = key.id().getPath();
        if (!path.startsWith(ARROW_PREFIX)) return null;
        return readId(path.substring(ARROW_PREFIX.length()).split("/"), new int[]{0});
    }

    private static Optional<HolderSet<Enchantment>> onTradedPool(HolderLookup.Provider registries) {
        var reg = registries.lookupOrThrow(Registries.ENCHANTMENT);
        return reg.get(EnchantmentTags.ON_TRADED_EQUIPMENT).map(t -> (HolderSet<Enchantment>) t);
    }

    private static String professionId(Villager villager) {
        return BuiltInRegistries.VILLAGER_PROFESSION.getKey(villager.getVillagerData().getProfession()).toString();
    }

    private static String enchId(Holder<Enchantment> ench) {
        return ench.unwrapKey().map(k -> k.location().toString()).orElse("");
    }

    // -------------------------------------------------------------------------
    // Synthetic key encoding + tag helpers
    // -------------------------------------------------------------------------

    // Package-private (not private) so BookKeyFormatGameTest can round-trip the key encoding.
    record SyntheticBookKey(ResourceLocation enchantmentId, int level) {}

    /** Flat-listing reference: the index-th ItemListing of the pool at a merchant level. */
    record ListingRef(int level, int index) {}

    public static boolean isBookKey(TradeKey key) {
        return key.id().getNamespace().equals(TradeOptimizer.MOD_ID)
                && key.id().getPath().startsWith(BOOK_PREFIX);
    }

    static TradeKey buildListingKey(int merchantLevel, int index) {
        return new TradeKey(ResourceLocation.fromNamespaceAndPath(
                TradeOptimizer.MOD_ID, LISTING_PREFIX + merchantLevel + "/" + index));
    }

    static ListingRef parseListingKey(TradeKey key) {
        if (!key.id().getNamespace().equals(TradeOptimizer.MOD_ID)) return null;
        String path = key.id().getPath();
        if (!path.startsWith(LISTING_PREFIX)) return null;
        String[] parts = path.substring(LISTING_PREFIX.length()).split("/");
        if (parts.length != 2 || !isAllDigits(parts[0]) || !isAllDigits(parts[1])) return null;
        try {
            return new ListingRef(Integer.parseInt(parts[0]), Integer.parseInt(parts[1]));
        } catch (NumberFormatException e) {
            return null;
        }
    }

    /**
     * Public extension API: the synthetic TradeKey for an enchanted-book trade at a given enchantment
     * and level. Add-ons (Trade Picker: Mastery) build one and pass it to {@link #generate} to get a
     * min-cost enchanted-book MerchantOffer for a librarian, reusing the proven book-generation path
     * instead of constructing the ItemStack by hand.
     */
    public static TradeKey bookTradeKey(ResourceLocation enchantId, int level) {
        return buildSyntheticBookKey(enchantId, level);
    }

    // Package-private (not private) so BookKeyFormatGameTest can verify the written format.
    static TradeKey buildSyntheticBookKey(ResourceLocation enchantId, int level) {
        // Level-first, all-lowercase form: book/<level>/<ench_ns>/<ench_path>. The level leads so
        // parsing stays unambiguous even though <ench_path> may contain slashes, and every
        // character is a valid ResourceLocation path char.
        String path = BOOK_PREFIX + level + "/" + enchantId.getNamespace() + "/" + enchantId.getPath();
        return new TradeKey(ResourceLocation.fromNamespaceAndPath(TradeOptimizer.MOD_ID, path));
    }

    // Package-private (not private) so BookKeyFormatGameTest can round-trip the key encoding.
    static SyntheticBookKey parseSyntheticBook(TradeKey key) {
        // NEW format (current):  book/<level>/<ench_ns>/<ench_path>   — level-first, all lowercase.
        // OLD format (pre-migration saves):  book/<ench_ns>/<ench_path>/L<level>   — uppercase 'L'
        //   marker. Still read so existing villagers keep their book picks.
        // LEGACY format:  book/<ench_ns>/<ench_path>   (no level marker) — pre-dates per-level
        //   expansion; treated as level 1.
        // <ench_path> may itself contain '/', because modded enchantments are allowed slashes in
        // their path — so we can't assume a fixed segment count.
        String path = key.id().getPath();
        if (!path.startsWith(BOOK_PREFIX)) return null;

        String[] parts = path.substring(BOOK_PREFIX.length()).split("/");
        if (parts.length < 2) return null; // need at least <ns> and one path segment

        // NEW format first: a purely-numeric leading segment is the level. Real enchantment
        // namespaces are never purely numeric, so this can't be mistaken for the OLD/legacy forms
        // below (whose leading segment is the namespace).
        if (parts.length >= 3 && isAllDigits(parts[0])) {
            int newLevel;
            try {
                newLevel = Integer.parseInt(parts[0]);
            } catch (NumberFormatException e) {
                return null;
            }
            String newNs = parts[1];
            StringBuilder newPath = new StringBuilder();
            for (int i = 2; i < parts.length; i++) {
                if (i > 2) newPath.append('/');
                newPath.append(parts[i]);
            }
            if (newPath.length() == 0) return null;
            try {
                return new SyntheticBookKey(ResourceLocation.fromNamespaceAndPath(newNs, newPath.toString()), newLevel);
            } catch (Exception e) {
                return null;
            }
        }

        String ns = parts[0];
        int lastIdx = parts.length - 1;

        int level = 1;
        int pathEndExclusive = parts.length;
        String last = parts[lastIdx];
        // A trailing "L<number>" segment is the level marker — only when there's a real
        // path segment before it (lastIdx >= 2), so a 2-part legacy key isn't misread.
        if (lastIdx >= 2 && last.length() > 1 && last.charAt(0) == 'L') {
            try {
                level = Integer.parseInt(last.substring(1));
                pathEndExclusive = lastIdx; // drop the marker; the rest is the ench path
            } catch (NumberFormatException e) {
                return null; // looked like a marker but wasn't a number — malformed
            }
        }

        StringBuilder enchPath = new StringBuilder();
        for (int i = 1; i < pathEndExclusive; i++) {
            if (i > 1) enchPath.append('/');
            enchPath.append(parts[i]);
        }
        if (enchPath.length() == 0) return null;

        try {
            ResourceLocation enchId = ResourceLocation.fromNamespaceAndPath(ns, enchPath.toString());
            return new SyntheticBookKey(enchId, level);
        } catch (Exception e) {
            return null;
        }
    }

    private static boolean isAllDigits(String s) {
        if (s.isEmpty()) return false;
        for (int i = 0; i < s.length(); i++) {
            if (!Character.isDigit(s.charAt(i))) return false;
        }
        return true;
    }

    private static List<Holder<Enchantment>> tradeableEnchantments(HolderLookup.Provider registries) {
        var enchRegistry = registries.lookupOrThrow(Registries.ENCHANTMENT);
        Optional<HolderSet.Named<Enchantment>> tag = enchRegistry.get(EnchantmentTags.TRADEABLE);
        if (tag.isEmpty()) return List.of();
        List<Holder<Enchantment>> out = new ArrayList<>();
        for (Holder<Enchantment> h : tag.get()) out.add(h);
        return out;
    }

    // -------------------------------------------------------------------------
    // Pricing source selection (config-driven)
    // -------------------------------------------------------------------------

    /**
     * Stable per-(villager, trade) seed. Hashing the TradeKey's string id keeps the value
     * identical between the picker preview and the eventual apply, and across re-opens — so a
     * randomized price can't be re-rolled by reopening the menu.
     */
    private static long priceSeed(Villager villager, TradeKey key) {
        return villager.getUUID().getMostSignificantBits() * 31L + key.id().toString().hashCode();
    }

    /** Cost source for flat (non-book) trades: min cost by default, seeded vanilla range if enabled. */
    private static RandomSource costRandom(Villager villager, TradeKey key) {
        return TradeOptimizerConfig.get().vanillaPricing()
                ? RandomSource.create(priceSeed(villager, key))
                : MinRandomSource.INSTANCE;
    }

    /**
     * Cost fallback handed to {@link IndexBiasedRandomSource} for book trades. Returns null in
     * min-price mode (so cost rolls pin to 0), or a seeded source when vanilla pricing is on —
     * the steered enchantment/level prefix is honored either way.
     */
    private static RandomSource bookCostFallback(Villager villager, TradeKey key) {
        return TradeOptimizerConfig.get().vanillaPricing()
                ? RandomSource.create(priceSeed(villager, key))
                : null;
    }
}
